### ISSUE TITLE
Compile Error on kernel 5.18

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8188eus#195] opened 2022-08-08 16:56 UTC
trying to compile on kernel 5.18.. parrot os but i get this error 

https://pastebin.pl/view/c3490a0d

it only works on kernel 5.15

**Comment by SimplyCEO** [comment] 2022-08-09 13:16
Duplicate of https://github.com/aircrack-ng/rtl8188eus/issues/187
Honestly... until no PRs get tested by OP, this error will be very common.

**Comment by ghost** [comment] 2022-08-13 08:57
what is PRs

**Comment by SimplyCEO** [comment] 2022-08-13 09:28
@voldmort21 [Pull Request](https://github.com/aircrack-ng/rtl8188eus/pulls)

**Closed as completed** 2022-08-14 09:32 UTC
